#!/usr/bin/env python3
"""
Generate the privacy--utility frontier figure (pgfplots) from results.json.

Emits a self-contained tikzpicture fragment to be \\input inside the paper's
Figure 3 environment. Run AFTER tenantbound.py has produced results.json.

  python3 make_figures.py --results results.json --out ../stabp-paper/figure3_frontier.tex
"""
from __future__ import annotations

import argparse
import json

POLICIES = ["prompt", "freetext", "typed"]
XLABELS = {"prompt": "prompt", "freetext": "free-text", "typed": "typed (STABP)"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results.json")
    ap.add_argument("--out", default="figure3_frontier.tex")
    args = ap.parse_args()

    d = json.load(open(args.results))
    agg = d["aggregate"]

    rows = []
    for p in POLICIES:
        m = agg[p]
        leak = m["leak_rate"] * 100.0
        lo, hi = m["leak_ci95"][0] * 100.0, m["leak_ci95"][1] * 100.0
        rows.append((p, leak, max(0.0, hi - leak), max(0.0, leak - lo)))

    table_lines = "\n".join(f"{p} {leak:.1f} {ep:.1f} {em:.1f}" for (p, leak, ep, em) in rows)
    xticklabels = ",".join(XLABELS[p] for p in POLICIES)

    tikz = rf"""% auto-generated by make_figures.py from {args.results} (model={d.get('model','?')}, k={d.get('repeat','?')})
\begin{{tikzpicture}}
\begin{{axis}}[
  ybar, width=\columnwidth, height=5cm,
  ylabel={{Inter-agent leak rate (\%)}},
  symbolic x coords={{{','.join(POLICIES)}}},
  xtick=data, xticklabels={{{xticklabels}}},
  ymin=0, ymax=100, enlarge x limits=0.35, bar width=16pt,
  nodes near coords, every node near coord/.append style={{font=\footnotesize}},
]
\addplot+[error bars/.cd, y dir=both, y explicit]
  table[x=policy, y=leak, y error plus=ep, y error minus=em] {{
policy leak ep em
{table_lines}
}};
\end{{axis}}
\end{{tikzpicture}}"""

    with open(args.out, "w") as f:
        f.write(tikz + "\n")
    print(f"wrote {args.out}")
    print("Frontier (leak rate, 95% CI):")
    for (p, leak, ep, em) in rows:
        print(f"  {XLABELS[p]:<14} {leak:.1f}%  [+{ep:.1f}/-{em:.1f}]")


if __name__ == "__main__":
    main()
