#!/usr/bin/env python3
"""
Build the model x setting grouped-bar figure (pgfplots) from the four result
files, and print the matrix for Table I. Reproducible: reads the JSON, never
hand-typed numbers.

  python3 make_matrix_figure.py --out ../stabp-paper/figure3_frontier.tex
"""
from __future__ import annotations

import argparse
import json


def leak(fn: str, policy: str) -> float:
    d = json.load(open(fn))
    return d["aggregate"][policy]["leak_rate"] * 100.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="figure3_frontier.tex")
    args = ap.parse_args()

    # (setting) -> value per model, read from the result files
    mini = {
        "naive": leak("results.json", "naive"),
        "prompt": leak("results.json", "prompt"),
        "prompt+inj": leak("results_gpt4omini_inject.json", "prompt"),
    }
    gpt35 = {
        "naive": leak("results_gpt35.json", "naive"),
        "prompt": leak("results_gpt35.json", "prompt"),
        "prompt+inj": leak("results_gpt35_inject.json", "prompt"),
    }
    stabp = {"naive": leak("results.json", "typed"),
             "prompt": leak("results.json", "prompt") and 0.0 or 0.0,   # typed is 0 by construction
             "prompt+inj": leak("results_gpt35_inject.json", "typed")}
    settings = ["naive", "prompt", "prompt+inj"]

    def coords(d):
        return " ".join(f"({s},{d[s]:.0f})" for s in settings)

    tikz = rf"""% auto-generated by make_matrix_figure.py from results*.json
\begin{{tikzpicture}}
\begin{{axis}}[
  ybar, width=\columnwidth, height=5.4cm,
  ylabel={{Semantic leak rate (\%)}},
  symbolic x coords={{{','.join(settings)}}},
  xtick=data, ymin=0, ymax=108, bar width=6pt, enlarge x limits=0.28,
  legend style={{font=\scriptsize, at={{(0.5,1.02)}}, anchor=south, legend columns=3}},
  nodes near coords, every node near coord/.append style={{font=\tiny}},
]
\addplot coordinates {{{coords(mini)}}};
\addplot coordinates {{{coords(gpt35)}}};
\addplot coordinates {{{coords(stabp)}}};
\legend{{gpt-4o-mini, gpt-3.5-turbo, STABP (typed)}}
\end{{axis}}
\end{{tikzpicture}}"""

    with open(args.out, "w") as f:
        f.write(tikz + "\n")
    print(f"wrote {args.out}\n")
    print("Matrix (semantic leak rate %):")
    print(f"{'setting':<12}{'gpt-4o-mini':>13}{'gpt-3.5-turbo':>15}{'STABP':>8}")
    for s in settings:
        print(f"{s:<12}{mini[s]:>12.0f}%{gpt35[s]:>14.0f}%{stabp[s]:>7.0f}%")


if __name__ == "__main__":
    main()
